/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTH1DPDF
#define ROOTH1DPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
#include "TH1D.h"
 
class RooTH1DPdf : public RooAbsPdf {
public:
  RooTH1DPdf() {} ; 
  RooTH1DPdf(const char *name, const char *title,
	     RooAbsReal& _x,
	     TH1D& _hist, bool _interpolate = false);
  RooTH1DPdf(const RooTH1DPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTH1DPdf(*this,newname); }
  inline virtual ~RooTH1DPdf() { }

  TH1D & getHist() { return hist ; }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  mutable TH1D hist ;
  bool interpolate ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooTH1DPdf,1) // Your description goes here...
};
 
#endif
