#!/bin/bash
#
if [ $# -eq 0 ]
then
	echo "Usage: $0 'sedpattern' <fileglobpattern>"
	exit -1
fi
sedpat=$1
shift
for file in $*
do
	newname=`echo $file | sed "$sedpat"`
	echo "moving $file to $newname"
	mv $file $newname
done
